# базовый образ
FROM nginx:mainline
# копируем конф файл
COPY jusan-dockerfile.conf /etc/nginx/conf.d/jusan-dockerfile.conf
# копируем распакованный файл
#COPY jusan-dockerfile /usr/share/nginx/html/
COPY jusan-dockerfile /var/www/jusan-dockerfile